forgejo_oidc_client_id: ENC[AES256_GCM,data:I7makd71wR2+upYtN1eLF9dgvayh9mY+InO2kXo8IbXBuJnZ,iv:HbLmho4jGonAiN7f7wB5RpO8oDtJ3qg6kW1QBFtD72E=,tag:emrg7K4U7g56pRmy4ubuoQ==,type:str]
forgejo_oidc_client_secret: ENC[AES256_GCM,data:x7BdNbflcr/JdrWDPtbVc+98f+uf28VbDtKtZ49bMrM=,iv:jTwPfotfvby5wHD0E+xcS6Y4/P7HU4eL/wg1wDT5sMc=,tag:vR2VB3vFrKNp1cfsY+RVMg==,type:str]
gitea_oidc_client_id: ENC[AES256_GCM,data:uCG8GWAcTE7nx9bf30uBXdNvlxS7Q+nKx45p3XgCzBUGd4B7,iv:xf/auv/3XfI183qUajrQmiFNSuKXJEA/ikV4ooCErgk=,tag:+Pa3tKvmtFIY4O5PsNn9Kg==,type:str]
gitea_oidc_client_secret: ENC[AES256_GCM,data:JFSHoam6fX7WtQK0BChyHKD6JGeUVMoQaRY9bggOdcg=,iv:1yh4ZOQEsat7r+4FkBxx/qA9Rp4R5yZ9rd6V8R79AJc=,tag:nQiKDnEuXWcvzY/+dWojEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aWlBby9ibDRrUlBxZEpZ
            OGt6RTYweHBnbmloZzlxaUR4QTJhcXZpTDJnCkVqYlJ6M0pMWklMd2NYc25oNzJY
            ZWp5RktHVDdOTXE1akNuUmoyMW5kNUkKLS0tIE5nZE02K1B2QjBZSmVjNlBhamVX
            ZHNMaDNwZGt1MnllRU9NTlJOREFOdHMK2kAoCkH0stR83Fi+qPBpyPdbHGTDExB0
            ZdPdcwkm+DzZZu/tN/8w3jIjDNBugJp5X6yVSDrP6jsOCn9seqvVug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T10:03:30Z"
    mac: ENC[AES256_GCM,data:rksr/u4SP825vSwu61oIyaIjDCbpRr1D5pexbG990emg7SIXWhQxlzg1EJ5jmLON2OQ/odct9ANxzryTcF2PiWFdRUHDBjedFmrp7DjHx92tbmrEhvbFMieGkm+COQwIvVbh92UKjeLzHC9pMwBAJ+36yrFwZ9l3WiQLHv3utpk=,iv:WqX2fAW2EHWP709XWRbN4taCrLdpVvhT63N3C/wEenY=,tag:7JVZrNBF36U3qIhiJVgCaQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
