domain: ENC[AES256_GCM,data:Scvw1vshEQ==,iv:p5S5f5lO25dhbW5A4Zn6sv71zftGb3e0JPYmWdlvkyc=,tag:LdYN5SQwVcBTvYRy7VwDUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSlZ6NVpFQy9HeXJuVmpX
            Y21Ha0RjZ2xvQ2N2aE02b01KVk9xQUhVT0hBCjU4cjhSelMyUlNBVnVpaDU0U3Fo
            dC9RQmdyLytzUnkvYlJQUW5zZGR5cjAKLS0tIFZqcXFPTmxwMnUwODN2OU5tSlox
            QWRneEFhT1dkdmZESDFJclRGSVdIR2MK1+VeT+4cH/207ETN230X9TH+88nSZjAf
            MiWy6fyM9W+nQ1D+Org8MaJcLhUbCJ60/UyJkZ3XGemAq/Z1O/zDTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T08:23:59Z"
    mac: ENC[AES256_GCM,data:ofwr3T2i0ZhI7bgy8EGgaWCtJbyfxJaIS45yozCL66F4abE6SMMZC2uenKNRfj6qCm3uYAuYwhcqlQDGSbeNcjFv5/fPy4sK1D11GbYEIhMee7d70jIW6Z1qrXqQbyFyY1gsCGHbSn0sfxs717hj8RxkuAmSFG65h1P8lR6nGLY=,iv:YkU2G+yLDdSeIhZVxjQ28rDa/Wcwit+Iuhocm/gBmas=,tag:aiN0+n6nfW7dCFDdwcz6ow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
