#ENC[AES256_GCM,data:eYpUvHGTuvcgnngAYDiUS/ssn0Xojcl5vXvusMID0UAPhS09XtJ39nZYXXg1AcZ+lOtHQFzMedA6dD+5+IRGd9e6TyW2XSnI,iv:kt9uwdYyWAkY8j4tQlfWlveDTYSPpt6XjNqIa0Uc8Wg=,tag:eAsiWAPe2EHMF/LGAdApVg==,type:comment]
domain: ENC[AES256_GCM,data:30mz558+Cw==,iv:5gS5DW9ms62OlFsL2fV2EOY5GR9IktmuZ/ahPg+p7es=,tag:CU0Tn1m+rR0A/Ae4lDReEw==,type:str]
hive_ssh_private_key: ENC[AES256_GCM,data:FjYLTh1/ZvdsjvAkxb+RDixQNpe/PZ9AOo6WxJRgH9EmDEjWWc0r6lBp8tkU69ds77diiGCSwZGryrkfU7hlna6z32hqqa58G+2QKOc//elqNbYG0Tm20jinwH7aZK1ndlhNXX7y1sK5ts766ZlsAowxS7ksbjnxYE977C8MtCTftV+Vv1V+R0O2Ul4huozPCbWf5ThknsPv4PtQ6qHaH7sbsDpng5gMLAKZFB26dSA0O4E8DW2uIznXCjHgwosEc6evA7RF3+41qRx2vg9FsI4YjZpGGC+3CQHVrVMboKsUSSb3xXfCo+t9QA48gQBVsj7K2y/p44SmOC9jouRyeT6PnWTk92YzPEjtKIjkHX0n8cs7RC3cQsthCo6PrF9xvKJ2VAOK3jPse0h1kWggJtTAx1lnNw9jtFb6G+MV/aZdPoZC08azUB8gnVZrAT2DIX+RqFHX36n0yfcuHow/ocGDMQE+uS8+tTJgyUJBxedbrdRGUlLUPmfoUuCrC/2VbyaUtmCYlNS5WkvmXN/J,iv:1tTWrW0O0KzcFbFaUMhIuODa+t6InHe5Gh6ncXu4UwY=,tag:+D7tZ84XwBIJOD1SGWRyKQ==,type:str]
hive_ssh_public_key: ENC[AES256_GCM,data:R0xXzP8AQeQW2wQCgJy80x3T+0qlKoaycFcDu/KqpqSNK/SYKtblUbVSOQtYmZ84pvyLkkMLKzH4Y+mv5Fo6HB78zRnOQI+EUAZQcIMLZILl8eudKSRZ+pw+6T2/vw==,iv:cu+svxb9LnSVApavG/wwuIJdwLcC7xbpt4faMBwKo9c=,tag:UBmnAE1pjFWHICzck1u7Pw==,type:str]
hive_node_user: ENC[AES256_GCM,data:KjpdKg==,iv:9m1/xVoPhlJwUaLPV1408QzUgvex/M62LWc+J52vlqQ=,tag:T9zvF2r2oRBADD4WVjgewA==,type:str]
hive_gitlab_url: ""
hive_gitlab_token: ""
hive_gitlab_username: ""
hive_github_deploy_key: ENC[AES256_GCM,data:Ji5xjZhCCySQxWVqnTx59yisD0+FThbiCKpOQ09ZSckexC/R23IjjoelHfwQIYrFWPHBi5XlLG+3BuwhIk9v5H+ESR0Da6izPnJ8kwV1NbQK4rWlj+BdF4TS69739/j6+rYLJIJQAd8Uo2//SLFba9f4zL49oF45vIv9Hq+YrjuMIInRq3AMQq7LzMjBAa/x594NBpLYpu4j3dgykZlPdbEPOLQ6Gvzu3SpfaXJBjm+BPaUcerT+zCtBPaG1PTFzUpSiACPQJFQljyQ3y/eaUJxIitr2UJARuzRzZevmzdyl1dWhfXUadaXo+BC6kR5IIHpoXyc/rJ61zs9CJKYi/1s+G100PHNYVUCbXBaNLaBJZuz1WhtZ73bhMhByxuGJ7WsesrPLwJT04pMm1j3r/r7fYAdGx/DwLDumNxCrepTOXTY6Wq1x3gbvYE+RoQ0KJRuXr/vfNqMU4MgnknKrt3vDuXneZFqQTVpa0nXgtxvKexXxuQvGm6X0Q+AoSEJW21JtK4sMmhnZMh2P9rmz4wbpjGBXIUbt+NKp,iv:GFYvu7GHIjFFHK295x1WycPy85AYQEwIu7FizvYaYoY=,tag:z1URX+sJT0NR4VaT/2GxCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAramI4UXVMb28vVGQ4QzY5
            bWlPK1hTZkExTWJ2SFpzMlJXdjg5VGdnVkdRClNOd28rd24wTTB3WGFuUk9vSTBo
            Y1JnRCtNZURqbEpJT3Jxd1ovcmIzMncKLS0tIDVlaTVmbGcvZzlBYTZyckg5UEpm
            bW5HRktnTDVKbjdPbFBFdVhpOHc2NzQKPCRNrMWSTMiEnkI/NfFCEvlYzhFpv26G
            1YrxEU+vzhTCo/bVMJnLnH7zPETuMMt8Ek69xtCTJO6zwQsaA8b2dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T22:19:36Z"
    mac: ENC[AES256_GCM,data:BGJbL9qSwgfPvv3tWDoUu5tu4bKBDt0yy3alB6UXie/RfdObWFjcsfi1yWkb7cU0SoMxqq+j6Ur6OGpTr5ytoxMYqBVBLRjQH50bpibw6f4OCi/iu8ZJm4YMzHexgiCA7d5zVR6+guXO50sm1H22JpyGklfqUP8EvRdHiYqwxFE=,iv:6y4T5Wq7pUNNvmbY9qr8yqv5r9/aR7hS5/FoT9S6+Io=,tag:HwPxBj0DVF0//DkIyjk0cQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
