forgejo_admin_user: ENC[AES256_GCM,data:U7piZyC/,iv:DYyKPrXQNDfAJRPnE6jJyJvZ4va8JtL6IIdlgNUor9c=,tag:pCZ8Ax2ffM1XRMxmz5+0bg==,type:str]
hq_allowed_email: ENC[AES256_GCM,data:j5o4jzhnN3HLNfLXmOVTQQ==,iv:Liy8gNLSTvdG42CrRJ8qyQdQrdJLGo6MuZuVs08/HQA=,tag:A1/9/b0bE29y7om6FBLc+g==,type:str]
forgejo_api_token: ENC[AES256_GCM,data:e2++qIuJarOteSuHwo4t3SlgFzdy/7MYKIzimXKtgLzn6F8zygPBBw==,iv:9TStGuUWfgQK+kNCIwwpB+CYTjk1w9VDjM8wWFtT730=,tag:oc7B0pkecII654QILdfQ+Q==,type:str]
hq_ssh_private_key: ENC[AES256_GCM,data:JejnSk6aoAvLcil9THc5K6OO5i1M4XJf+ay6w1BwNnWd1n5hzBz1D7QSV9QniVSckPH3bUXbqxmVbNLUsbWweHRcpG3kCL4wKTI69D+7ZrTmTJipX/ewmcMKXe2dZ5m1EUAS6ILT1C4UML3gVcfcET6lqk7+FuyTQcsq+TFk+Yqr7Os3dFQqcC4ZwEE4AORmCCh5/V3SWhvQyNxGjUIl9kfUu21RiGz7EKMmLIZcwOW6ujD1ZDJm77cBeyXHCuiEMrxQKkJcoHWJahajtUj+Xf/NxLjAZZZ1CFg/sVOfnvyJ7kIcHprjv/WtGndFvBTF3dEYdPpS0waDhkodLVAFAWt6PM8RGxn2KAfyTaeH8enBP7DiE/wocrHbM1dqUVkVNy7/PRBc/I+tGDfNAyIijUGVLhHloqRbCrUFuepVIUDsAf9IJtev+z599US8F2rs6k60g3SanJLcGIBJ+o55epc0FQqRnC5G4rrwsraFT+DekK67fKpDwQ1CG0EahOrM0toHrB/5YNJP2E2jxnw3,iv:kZi+TPukvu6ksvJcdajKOSXDar91xHCVK0Obiotcdw4=,tag:3xjpD+2ttCdrmuW4AImd/A==,type:str]
hq_ssh_public_key: ENC[AES256_GCM,data:HbIcEo5ANIuy0qFFs6byBYltq34nWCjpNjuM5afKvWVMWjwW35sUyux+YHwPayuVo9xoyopQS2hGjQ1ClJaHLsg+Wea+18y6mUoHuTX+FqDwwyTWndmoBF1VUA+bSQ==,iv:yd5AUlOevlIwMkqizeY4CHKcVWwTGjSmTvhEMb09v7A=,tag:RfDPHXll180rx+Hc9qmvmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKalgrQ05lbzFoREV4WjJF
            ZG9FdkJVbGZLVlNlT3BKWFEwM05TTlpHNUVBCmxUbTZXLzVVUmhsdlBJSURXRjU2
            Y2U5LzNkdHhBZzFWOFM3SGFJaW9WOFkKLS0tIDczdERuQm4ydkI1R2QyMGU4bFd0
            a25WcVBYRkhoRzZiR043eTJGNUF1WEEKjMfLD15vU6kbB3wvLx3wSCoVSSUbmkxf
            9Nr+knbatXrYBdz4KxhirehsdPzWpDIV1nqWLvNhte03dWhfyxp2gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
    lastmodified: "2026-09-01T15:55:18Z"
    mac: ENC[AES256_GCM,data:OhYeY9k1NGFp0wiZkOlUIlBF+qckSheDU//tPdMZUccCfB6NKf+i4JuAf4o158aY2WIYR3jM+zuQRxDXs9Ab7qS0yV01FRHip+iiqqDV4SN+8W/mWdWyQPwZTuuuJjphtzIupspqLX4cQCze3OTdS4cxkThuF9ilxkhEzWw2aHs=,iv:YYf6sfMiPpyLaD0Ie5DMOW2WLXJiqK0swq6RROSh/BI=,tag:rFTi2omwNrpwKv+uxOP4Pw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
