deploy_key: ENC[AES256_GCM,data:tahlJOsb49qBQpQeCKFKUqll5w6j7kNFC64umHMY3htUcYZOQErsb5wGEuArD7yhSlyhPtO+lKiXv+5MZnMdbc8ehbSAaAe6h3dw+13+T4Oa7Sq3+/XH7DoBVQl8lYcnhNiZY+BYheFjs6s6vcrRWWwAc5fa8zVDTFprhnBKdm6BgN1VVc/li/uTS0Q/BpaZ27aLE5Gb0ypp6KXnX/bS/l5HQZvGlsSX7ZRxwrDpCSv+kDWy2bc9+sDICa34sez7zUMDXukoBKNK5XLL/123IvNrrdWtCxAV3zYZov5bZSLq/fY7AUinxPnDHRiXSpvhbEa7t/onRu+RNHtUAu6D1473KMG/EkRWgT0+e1dIi36IxC4yJGMDuqBJiN5mmNW6nSZ6Ua2vkwXQjcxh9er8vY4BLyVTaNsLm4mIio4LnpeaHQJ+B5oq2ARdWdrz9No5I23TMdhWowwgZUB81WK1xrNMdrlTGk8f+q/dYjiUyfysZbPSxSVyGXClppNGlLUb/DvLGdq+1v3Fc5cHewMYKQc6MJZLmxzKy/oB9AQv0ij3OMY=,iv:48Ghw+pPk1xaTp2csF9QwpLvAax4td9yuelU3km58dc=,tag:JguaN/Kr4WXMe7opaeNc9w==,type:str]
api_token: ENC[AES256_GCM,data:UJfpdl5Fg0YrIauPhxJ+UKEh4qOvj7Ti9cRPEEnG5ATr6IIWy8jlhhIpR/XRUhd8tDhrA+x/rmtG9Vus87eLzg==,iv:mMmm4BhBnR+YmZkQczm8XFG5cbbj4cfbTx+KocysA/0=,tag:TbEG4XuEk4NJiLm5ewDWJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzczdCUU9CUlhoekZ6Qzcw
            UjB2S285ODVCRUJDS2d6UUVKMDBGd0VuN0VvCjdEWHl5Tnd1WVFXRUgwMURlYW9Z
            Ynh0SGVSaUlPNnRoK21DSzhYVnpMSlkKLS0tIHkwSVAzWDBEUmo1djV5c3lTY0JE
            SFNERWM3TlhZNmZ6VnZBRkVaenI5VzgKdLfwlo13A0tl9xgeX4726+m7LTovQb18
            m/MqcxqCGf3A1WP1nWtxO9Lx5uMo97SNWKi63zljogWEzXmbHPSl3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
    lastmodified: "2026-08-24T15:36:04Z"
    mac: ENC[AES256_GCM,data:ZghZ5CRw+MD7o+KVTip8o3CwgBhaC7a7BwKK32x7Zd3FGFgDhCGyHrPvJyEk8EICvIsjNBNZqxRZH4E9X9BlR28YdGeI+/x1KIdT8fB8i23mSz8hB5jxz0UrWnVXAWqNZyrlbY7sVyLE7KukkdiOvlxVp5hq7JvrmVkpywJG59w=,iv:7H+bpoV81kFBW4Sa3QhIQ3YT5mUEL7Yl+419qRI9aq0=,tag:ldPoAhnnILq5wO+QqURdbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
