#ENC[AES256_GCM,data:izvm0DK3kVmy0UqJGjr7hwRxwpvJzhka/Ix37bmeykhjMulCLyRLz3jcsKxISA==,iv:EF3OqJR0K73DVItEzdbA3fBSIEvmQ5MW4yUMrqs6nsk=,tag:qhfQF+bOTmdp6YUSZbVPxQ==,type:comment]
todo_deploy_key: ENC[AES256_GCM,data:YOKeFpmkm4PYXrumzBuvmb0gFVU9bpu02p8WgkmPZTSJF4CF3OF+W7xZ24gxGwuKoCn1WQx8XdB6Q8P86YmXQVNR/jc02PYuK39KziSQcspbvH5R7yD6IzOTXTsudwrYqDKk/kNDyDy+1naLplf5tVWhDp4YiwaFGrIC27kns03cUv6Pk0OdFga0YenX6rBBOKolGPnpAb4Nn9p5aA5zxqktT859CWYlbZUe5214xnsDvjFfI/DhTypAjNUbRHu1WMGOE4VqZ0gx6xa7DCCcpGHyheiB7GaB1Us38OCw3Z+JN/qWarEy2ES2KXInV1WNNmHwaFptVK7t4ofuw31wB12LSMXCX9dZ2JixmVr0CiaA1jhjF+w1XvqPzbInFUAtZh26jRtQBagQrSnbNYhCph8g/omjsatslyqvVqP3DsD4/LEyL4sUyWwW5kv2+sTWjlHNmz7eRiMdDkJQEdjlO4n6nE/xd4gu6Ywo1J10ozh2LiDUuGXoeu73bqNrDzGyiHeZ822n/1kW1EJEZaY7gX4QayOiulgna/0U,iv:AdnDRUasfT4B1/sZcEImqKTs5eyoNHifB0GRwcsVKro=,tag:kz8B8ZYFxr3U3DHQ2x/psw==,type:str]
ntfy_user: ENC[AES256_GCM,data:2XAwtA==,iv:Bk0mqacjonGiAsgeVH8yUi2wN9p6dlcSpCbmvTRjF2Y=,tag:yju6QpbA3UweMV+/avR00g==,type:str]
ntfy_password: ENC[AES256_GCM,data:IKZP6bajYzMic0WyBkjpj9jzPcYHmOc=,iv:1aGGIWGVeToPhapB29g/YHE96ycbJkZzPuIlCnPsBYY=,tag:AwQIZ/Pr+YoA7hYzQfK4kw==,type:str]
ntfy_topic: ENC[AES256_GCM,data:p41thTTq4Q8LED9LYaTOHVI=,iv:0fp8DICZlZI3Y1KN62CnUVg95yNs4AES5vZOKP03jfo=,tag:E7uu8nxkeI7IRmfyNvcoBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByb21pRVpPR3RkWEtLanlV
            TFN4dkplbWs1VzdEdTlZNlVqMm15cnJTNHdRCkJHeEJjbHc2eVJzbSthT3pmWllJ
            a2dtYWREaU9ubFhma1VMYWtGRWNla2cKLS0tIFh5azFodzYwSVZxM2JaZzIxejJW
            aHRzd2xCVzZZMXBxRmRaVUgwVnpOTjgKvMXQ+4WK7PcA2No/uCEIgZtxmAqJykoS
            g2a9y071FrziTWFGmbWN0+qTafSjK7k4TnnRD5TxhIMbpeN9dodI9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T18:02:33Z"
    mac: ENC[AES256_GCM,data:gR+HCs9A7uMHjZ1us9w5gbptZNKmPEqZHR5DetHnupzLdwIvbgLADjJq60Zb0qHJb7APmZqOpiKeYOXm/gIQpFlmM1lILKXFHeMkuVFbUxLiWBNsiXCLmBdsIenPfHgU+qKv5cGEdP9puLviSSQ9hAV2E5uhoaUE9dCrp66c0hw=,iv:4NQsQkenKQ5y7R6sZcd1RNmWpZX9wiT2SKxTGqwhtWI=,tag:VtMQeXk0OHunnP73MdhiXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
