#ENC[AES256_GCM,data:UKCbqymPKUsVSTWqUJiZqT1Lcgut/HoiYC9xYkjwhukQK57rnoOvSbA43XoDLRa61RNGJ9za2MZ/yg==,iv:XeYrCb1acRBkt66b/X8MN87XjHx44raL0NgReg/SDU0=,tag:f5UH9f5rupC3iNDqn7TwQQ==,type:comment]
torrentleech_username: ENC[AES256_GCM,data:FRWZUvOVxdOyDw==,iv:SfCXgiQ0eRSks9fRGbsBKCGPAp3adKYJNg9ekpgb4p4=,tag:pfpk/Fg3KGBOK7tYklIhnw==,type:str]
torrentleech_password: ENC[AES256_GCM,data:34oO9Bzkrcm9P5ePNzWFr+ykWaKUCW//dV3TtI/sH+UD7oFl6F7/Gk4A8szminl67keKNEG8zwtV+CV9wMLQiw==,iv:kxXLoF1iNxYQFVM6jq4gNplcHLV/gm2daSYWgD00IMo=,tag:TqzYYx3J6pptXp3/0PSBqw==,type:str]
torrentleech_rss_key: ENC[AES256_GCM,data:gx8DKa5xpVrZHC+ofFX1BB/yGac=,iv:ZjqQofzGNVCVHXWIzHBfvezoLwObEIRzJcP7QyNZom8=,tag:rA2Pr3bImWLBgcEf6eIcRQ==,type:str]
torrentleech_irc_key: ENC[AES256_GCM,data:ZctRQ/q9XRGGFexf4X8vxEMInik=,iv:rZ3HyWk3u0WVWonv2T78RlHeH6lxgVYrodEHmhhBou0=,tag:h+7oeJ9LLMQrjHgqWWbJEA==,type:str]
torrentleech_irc_nick: ENC[AES256_GCM,data:QlrDHJMhmSrXTgb6t9A=,iv:Av9TEVjYb76aktOdswJ5a69J2tf4siK3ntLxZ607Iho=,tag:BH4+fERC5/tg6ubFMJG7lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTTFqczdUdGRpVjZCaFlk
            V2hqckVBbmRYUUc2N0ZpRExIdDV6NlQvbDAwCk1iZjE4emMyemYrZHJvSUlXUkpG
            WjlmKzZmbVJ4dVdyMm9GQXlqSDdYZkkKLS0tIGVScVNNb0VGVWNXd214NTR6cFVh
            YmlIOGY3NGFSbzRIdnF2VEM4VWJ1L2cK8d49on98pVO+ctTSJN8mSsP9ndQU5Qu5
            5dufaTF+foCuk1wf1CcO/uQIqKennDC+kkvJgs3tGoKGTiMKqR7UXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T18:55:40Z"
    mac: ENC[AES256_GCM,data:S+DuyyRkJuAIqONwjVytxkH6kWGr+Fqk+GrHax1mKt4dUwKQbeN++01APGS2/Vknoab5RWq6BkydJ0BoKHzvt62Y/Qwg/Jmy1hCZJ5gg6mkqXAJC2SxSzTR4ZOV3z3gFavMwY3axVcvLCJx0+R2WQ/hlUbm3Q4SiStF3Z/S+fo8=,iv:k+XcvCTd+YczY0nK96JPdpM8M3bSzUNeQ1Ru+SUp7vk=,tag:h7NPlPiQSZyifsFUM8NqGw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
