creation_rules:
  # Docker secrets (.env.sops files)
  - path_regex: docker/.*\.sops.*$
    age: "age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws"

  # Ansible secrets
  - path_regex: ansible/secrets/.*\.ya?ml$
    age: "age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws"

  # Install secrets (Proxmox answer file)
  - path_regex: install/.*\.ya?ml$
    age: "age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws"
